#!/usr/bin/env php
<?php
if (version_compare('7.1.0', PHP_VERSION, '>')) {
    fwrite(STDERR, 'phpsu works only with php version >=7.1 your version is: ' . PHP_VERSION . PHP_EOL);
    die();
}

const COMPOSER_INSTALLATION = 0;
const GIT_INSTALLATION = 1;

call_user_func(function () {

    $possibleVendorPaths = [
        // php ./vendor/bin/phpsu
        __DIR__ . '/..' => COMPOSER_INSTALLATION,
        // php ./bin/phpsu
        __DIR__ . '/../vendor'  => COMPOSER_INSTALLATION,
        // php ./phpsu
        __DIR__ . '/vendor' => GIT_INSTALLATION,
        // php ./vendor/phpsu/phpsu/phpsu may be symlinked from ./vendor/bin/phpsu
        __DIR__ . '/../..' => COMPOSER_INSTALLATION,
    ];

    $firstVendorAutoloadFile = null;

    foreach ($possibleVendorPaths as $vendorPath => $installationType) {
        if (file_exists($vendorPath . '/autoload.php')) {
            define('PHPSU_VENDOR_PATH', $vendorPath);
            if ($installationType === COMPOSER_INSTALLATION) {
                define('PHPSU_VENDOR_INSTALLATION', true);
            }
            $firstVendorAutoloadFile = $vendorPath . '/autoload.php';
            break;
        }
    }

    if (!$firstVendorAutoloadFile) {
        fwrite(STDERR, 'phpsu could not find any autoload file' . PHP_EOL);
        die();
    }

    require $firstVendorAutoloadFile;
    \PHPSu\Cli\PhpsuApplication::createApplication()->run();
});
