#!/usr/bin/env php
<?php
if (version_compare('7.2.0', PHP_VERSION, '>')) {
    fwrite(STDERR, 'phpsu works only with php version >=7.2 your version is: ' . PHP_VERSION . PHP_EOL);
    die();
}

call_user_func(static function () {

    $possibleAutoloadFiles = [
        // php ./vendor/bin/phpsu
        __DIR__ . '/../autoload.php',
        // php ./bin/phpsu
        __DIR__ . '/../vendor/autoload.php',
        // php ./phpsu
        __DIR__ . '/vendor/autoload.php',
        // php ./vendor/phpsu/phpsu/phpsu may be symlinked from ./vendor/bin/phpsu
        __DIR__ . '/../../autoload.php',
    ];

    $firstVendorAutoloadFile = null;

    foreach ($possibleAutoloadFiles as $file) {
        if (file_exists($file)) {
            $firstVendorAutoloadFile = $file;
            break;
        }
    }

    if (!$firstVendorAutoloadFile) {
        fwrite(STDERR, 'phpsu could not find any autoload file' . PHP_EOL);
        die();
    }

    require $firstVendorAutoloadFile;
    \PHPSu\Kernel::run();
});
