#!/usr/bin/env php
<?php
if (version_compare('7.1.0', PHP_VERSION, '>')) {
    fwrite(STDERR, 'phpsu works only with php version >=7.1 your version is: ' . PHP_VERSION . PHP_EOL);
    die();
}

call_user_func(function () {
    $possibleAutoloadFiles = [
        // php ./vendor/bin/phpsu
        __DIR__ . '/../autoload.php',
        // php ./bin/phpsu
        __DIR__ . '/../vendor/autoload.php',
        // php ./phpsu
        __DIR__ . '/vendor/autoload.php',
        // phpsu from current working directory
        getcwd() . '/vendor/autoload.php',
    ];

    $firstFileExisting = null;

    foreach ($possibleAutoloadFiles as $file) {
        if (file_exists($file)) {
            $firstFileExisting = $file;
            break;
        }
    }

    if (!$firstFileExisting) {
        fwrite(STDERR, 'phpsu could not find any autoload file' . PHP_EOL);
        die();
    }
    require $firstFileExisting;
    \PHPSu\Cli\PhpsuApplication::command();
});
